"use client";
import Image from "next/image";
import Link from "next/link";
import { FormEvent, useState } from "react";
import styles from "./auth.module.css";

export default function AuthForm({ mode, token = "", invitedEmail = "" }: { mode: "login" | "register"; token?: string; invitedEmail?: string }) {
  const [email, setEmail] = useState(invitedEmail); const [fullName, setFullName] = useState(""); const [password, setPassword] = useState(""); const [show, setShow] = useState(false); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); setLoading(true); try { const response = await fetch(`/api/admin/auth/${mode}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, fullName, password, token }) }); const result = await response.json() as { ok?: boolean; error?: string }; if (!response.ok) throw new Error(result.error || "Unable to continue."); window.location.assign("/admin"); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to continue."); setLoading(false); } }
  return <main className={styles.page}><section className={styles.visual}><Image src="/images/hero.png" alt="Luminix Shades architectural interior" fill priority sizes="(max-width: 800px) 100vw, 58vw" /><div className={styles.shade} /><Link href="/"><Image src="/images/logo-white.png" alt="Luminix Shades" width={190} height={54} unoptimized /></Link><div><span>PRIVATE ADMINISTRATION</span><h1>Designed for<br /><i>complete clarity.</i></h1><p>Manage every lead, conversation and project from one secure workspace.</p></div><small>SMART FILM · MOTORIZED SHADES · CUSTOM DRAPERY</small></section><section className={styles.formSide}><div className={styles.formWrap}><span>{mode === "login" ? "WELCOME BACK" : "ADMINISTRATOR INVITATION"}</span><h2>{mode === "login" ? "Sign in to your workspace." : "Create your administrator account."}</h2><p>{mode === "login" ? "Enter your Luminix Shades administrator credentials." : "Complete your profile to accept this private invitation."}</p><form onSubmit={submit}>{mode === "register" && <label>Full name<input autoComplete="name" value={fullName} onChange={(event) => setFullName(event.target.value)} required /></label>}<label>Email address<input type="email" autoComplete="email" value={email} readOnly={Boolean(invitedEmail)} onChange={(event) => setEmail(event.target.value)} required /></label><label>Password<div><input type={show ? "text" : "password"} autoComplete={mode === "login" ? "current-password" : "new-password"} value={password} onChange={(event) => setPassword(event.target.value)} required minLength={mode === "register" ? 10 : 1} /><button type="button" onClick={() => setShow((value) => !value)}>{show ? "HIDE" : "SHOW"}</button></div></label>{mode === "register" && <small>Minimum 10 characters with uppercase, lowercase and a number.</small>}{error && <p role="alert" className={styles.error}>{error}</p>}<button type="submit" disabled={loading}>{loading ? "SECURING ACCESS…" : mode === "login" ? "SIGN IN" : "CREATE ACCOUNT"}<i>→</i></button></form>{mode === "login" ? <footer>Need another administrator? The account owner can send an invitation from Users.</footer> : <footer>Already registered? <Link href="/admin/login">Return to sign in</Link></footer>}</div></section></main>;
}
